version: 2
services:
  demo-app:
    git_url: <https://github.com/Goosepa/radiant_verse_bot>
    git_branch: master
    ports:
    - container: 5000
      http: 80
    dockerfile_path: Dockerfile
databases:
- redis
